
include: package:flutter_lints/flutter.yaml

linter:

  rules:
    prefer_const_constructors: false
    prefer_final_fields: false
    use_key_in_widget_constructors: false
    prefer_const_literals_to_create: false
    prefer_const_constructorss_in_immutable: false
    avoid_print: false
    non_constant_list_element: false
    const_constructor_param_type_mismatch: false

